### ISSUE TITLE
I want to know input attack address and you can fix "Bot not automatic for some moments"

### ISSUE THREAD

**Issue by Hyundai0** [qellzXan/Tekken7_auto_low_parry_throw#2]
If i want low guard i just must not press w a s d keys. Because when I press the A key for guard, if the bot is working,  but can't double input in tekken, so bot can't input the sitting key. bot is only valid when I don't press anything

https://streamable.com/2uv9ne
like that video

so i just want opponent's input attack address 
low attack address is "int low = 0x20000112;"
i just want to add "int attack = "address" because i dont know input attack address. please find input attack address

So i want to bot press the A key automatically when opponent attacks you Then you can only guard when opponent attacks, and for that reason, you can completely guard or parry low attacks

**Comment by Hyundai0** [comment]
I'm explaining why the bot is not automatic in some movements, because you said, "Bot not automatic for some moments." You're gonna have to fix this

**Comment by Hyundai0** [comment]
> I have added many features but only use 5-6 of them. For example, there are three main ones. https://streamable.com/ach5q0
> 
> https://streamable.com/svks59
> 
> https://streamable.com/ddkcd8
> 
> but I can't show them to the public

anyways example for backdash when oppenent input attack : https://streamable.com/hukoum
that bot is not this it just other punisher bot

**Comment by Hyundai0** [comment]
I like to study Tekken bots these days or have fun with Tekken bots

**Comment by Hyundai0** [comment]
if you want to contact me please add friend on discord Hyundai#0507

**Comment by qellzXan** [comment]
I will update in 5 minutes

**Comment by Hyundai0** [comment]
> I will update in 5 minutes

thanks my man, I am very interested in Tekken bots these days, so I found it interesting to find and study and try to edit sources Tekken bots except for what I have, and I feel really good to find your great bot on Github yesterday

**Comment by Hyundai0** [comment]
> I will update in 5 minutes

it is any new functions?

**Comment by qellzXan** [comment]
> 

I guess yes

**Comment by qellzXan** [comment]
i abandoned the project. Now I am working with java projects.
When I have time, I'll post it.

**Comment by Hyundai0** [comment]
> i abandoned the project. Now I am working with java projects. When I have time, I'll post it.

thanks

**Comment by Hyundai0** [comment]
how to use combo.h i mean what is hotkey

**Comment by qellzXan** [comment]
this is a finished function. To use it, you need to write its name in the main and ();

**Comment by Hyundai0** [comment]
Tekken has a low attack that can't be parry But your Tekken bot either spills this, or automatically attempts to enter a hopkick. kunimitsu 3LK RP has a low attack that you can't parry [ like noctis 3 rp ] Is there a way to automatically prevent the bot from try a hopkick or low parry? Before the bot was updated, it was possible to just guard low attacks

**Comment by Hyundai0** [comment]
how do you find memory address? some players try to hit unblockable attacks i want to find unblockable address and tackles address and murdoc tackles address. you find it them on cheat engine or what? please tell me

**Comment by qellzXan** [comment]
> how do you find memory address? some players try to hit unblockable attacks i want to find unblockable attacks address and tackles address and marduk tackles address. you find it them on cheat engine or what? please tell me

Reverse Engineering and Memory Hacking with Cheat Engine

**Comment by Hyundai0** [comment]
> > how do you find memory address? some players try to hit unblockable attacks i want to find unblockable attacks address and tackles address and marduk tackles address. you find it them on cheat engine or what? please tell me
> 
> Reverse Engineering and Memory Hacking with Cheat Engine

https://www.udemy.com/course/reverse-engineering-memory-hacking/ this?

**Comment by qellzXan** [comment]
> > > how do you find memory address? some players try to hit unblockable attacks i want to find unblockable attacks address and tackles address and marduk tackles address. you find it them on cheat engine or what? please tell me
> > 
> > 
> > Reverse Engineering and Memory Hacking with Cheat Engine
> 
> https://www.udemy.com/course/reverse-engineering-memory-hacking/ this?

try for free
https://www.youtube.com/c/GuidedHacking/videos

or this https://www.docdroid.net/rtoAc2n/game-hacking-pdf
for free

**Comment by Hyundai0** [comment]
> 
Thank you for your help i will learn it Thank you so much

**Comment by Hyundai0** [comment]
> 

what should i watch to help? i dont know where to start

**Comment by qellzXan** [comment]
try the book
