### ISSUE TITLE
Key Input Mapping

### ISSUE THREAD

**Issue by Hollowcard565** [qellzXan/Tekken7_auto_low_parry_throw#3]
Hello, I would like to ask what are the button configs you have on keyboard?

For example, your key in the code for your right punch is 'p'.

I have a different button config below. I'm trying to bind my own button config to your code.
J - 1 I - 2 K - 3  L - 4." 

Nevertheless, this was a good project. I really enjoyed learning your source code. Good job man!

**Comment by Hyundai0** [comment]
I key is left punch P is right punch O is Left kick K is right kick

**Comment by qellzXan** [comment]
> Hello, I would like to ask what are the button configs you have on keyboard?
> 
> For example, your key in the code for your right punch is 'p'.
> 
> I have a different button config below. I'm trying to bind my own button config to your code. J - 1 I - 2 K - 3 L - 4."
> 
> Nevertheless, this was a good project. I really enjoyed learning your source code. Good job man!


1 | Left Punch   -  i
2 | Right Punch  -  p
3 | Left Kick    -  o 
4 | Right Kick   -  k
